### ISSUE TITLE
admin password issue

### ISSUE THREAD

**Issue by wizardcos** [Umair-fq/Airline-Flight-Management-System-in-Java-Swing#1]
the admin password of the system is not mention plz rply 
the admin password and username

**Comment by Umair-fq** [comment]
try these credentials

username = Umair F.
password = 1234

I hope this will be helpful to you.

**Comment by wizardcos** [comment]
Thanx a lot brother its working fine…
Regards : M.Taha

**Comment by wizardcos** [comment]
Can you helpme out a bit regarding this project ???

**Comment by Umair-fq** [comment]
Hi Taha,
how can I help you out in this project?

**Comment by wizardcos** [comment]
So basically i want to submit this project to our 2nd semester final
project in Oop subject… so i want to change the admin login credentials so
if you can help out with this than it would be great plzzzz..

**Comment by Umair-fq** [comment]
Hey Taha, 
you can change the credentials for admin login in the MainMenu.java file. You can adjust them according to your own choice from line 60 to 67. I suggest thoroughly going through the project. It's really good practice to review other people's code, but understanding the code is also essential.

**Comment by wizardcos** [comment]
Hey umair,
I appreciate your help and i will make sure that i will go through the
whole project and understand it as well……
Regards : M.Taha ,

**Comment by wizardcos** [comment]
If i face any problem can i contact with you…??

**Comment by Umair-fq** [comment]
yeah sure, you can message me at my [LinkedIn](https://www.linkedin.com/in/farooq-umair-dev) account.

**Comment by wizardcos** [comment]
Thankyou for this courtesy
